var movies = [ {
    "grossing": 1004558444,
    "director": "Christopher Nolan",
    "movie": "The Dark Knight",
    "other": "sequel",
    "main actor": "Christian Bale",
    "release date": "7/12/2008",
    "studio": "Warner Brothers",
    "rank": 1,
    "Academy Awards": "Supporting Actor, Sound Editing",
    "genre": "Action",
    "rating": 9,
    "year": "2008",
    "image": "http://paulmmartinblog.files.wordpress.com/2011/07/the_dark_knight_poster.jpg"
  },
  {
    "grossing": 786636033,
    "director": "Steven Spielberg",
    "movie": "Indiana Jones and the Kingdom of the Crystal Skull",
    "other": "sequel",
    "main actor": "Harrison Ford",
    "release date": "5/22/2008",
    "studio": "Paramount",
    "rank": 2,
    "Academy Awards": null,
    "genre": "Adventure",
    "rating": 6.3,
    "sequel": "sequel",
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p19_zps3fcb9219.jpg"
  },

  {
    "grossing": 631744560,
    "director": " Mark Osborne",
    "movie": "Kung Fu Panda",
    "other": "Original",
    "main actor": "Jack Black",
    "release date": "6/6/2008",
    "studio": "Paramount",
    "rank": 3,
    "Academy Awards": null,
    "genre": "Animation",
    "rating": 7.6,
    "sequel": null,
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p25_zps56e303a3.jpg"
  },
  {
    "grossing": 624386746,
    "director": "Peter Berg",
    "movie": "Hancock",
    "other": "Original",
    "main actor": "Will Smith",
    "release date": "7/2/2008",
    "studio": "Sony/Columbia",
    "rank": 4,
    "Academy Awards": null,
    "genre": "Fantasy",
    "rating": 6.5,
    "sequel": null,
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p24_zps26639521.jpg"
  },
  {
    "grossing": 609842637,
    "director": " Phyllida Lloyd",
    "movie": "Mama Mia!",
    "other": "Original",
    "main actor": "Meryl Streep",
    "release date": "7/18/2008",
    "studio": "Universal",
    "rank": 5,
    "Academy Awards": null,
    "genre": "Musical",
    "rating": 6.3,
    "sequel": null,
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p23_zpse3142f60.jpg"
  },
  {
    "grossing": 2782275172,
    "director": "James Cameron",
    "movie": "Avatar",
    "other": "Original",
    "main actor": "Sam Worthington",
    "release date": "12/18/2009",
    "studio": "Fox",
    "rank": 1,
    "Academy Awards": "Cinematography, Art Direction, Visual Effects",
    "genre": "Sci-Fi",
    "rating": 8,
    "sequel": null,
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p13_zps14cb8139.jpg"
  },
  {
    "grossing": 934416487,
    "director": "David Yates",
    "movie": "Harry Potter and the Half-Blood Prince",
    "other": "From book",
    "main actor": "Daniel Radcliffe",
    "release date": "7/15/2009",
    "studio": "Warner Brothers",
    "rank": 2,
    "Academy Awards": "Cinematography",
    "genre": "Fantasy",
    "rating": 7.3,
    "sequel": "sequel",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p14_zpsa29c87f4.jpg"
  },
  {
    "grossing": 886686817,
    "director": "Carlos Saldanha",
    "movie": "Ice Age: Dawn of the Dinosaurs",
    "other": "sequel",
    "main actor": "Ray Romano",
    "release date": "7/1/2009",
    "studio": "Fox",
    "rank": 3,
    "Academy Awards": null,
    "genre": "Animation",
    "rating": 7,
    "sequel": "sequel",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p17_zps8595100b.jpg"
  },
  {
    "grossing": 836303693,
    "director": "Michael Bay",
    "movie": "Transformers: Revenge of the Fallen",
    "other": "sequel",
    "main actor": "Shia LaBeouf",
    "release date": "6/24/2009",
    "studio": "Paramount",
    "rank": 4,
    "Academy Awards": null,
    "genre": "Sci-Fi",
    "rating": 5.9,
    "sequel": "sequel",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p16_zps71e1ff5d.jpg"
  },
  {
    "grossing": 769679473,
    "director": "Roland Emmerich",
    "movie": 2012,
    "other": "Original",
    "main actor": "John Cusack",
    "release date": "11/13/2009",
    "studio": "Sony/Columbia",
    "rank": 5,
    "Academy Awards": null,
    "genre": "Action",
    "rating": 5.8,
    "sequel": null,
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p12_zpsfcfb1dbb.jpg"
  },
  {
    "grossing": 1063200000,
    "director": "Lee Unkrich",
    "movie": "Toy Story 3",
    "other": "sequel",
    "main actor": "Tom Hanks",
    "release date": "6/18/2010",
    "studio": "Disney",
    "rank": 1,
    "Academy Awards": "Original Song, Animated Feature",
    "genre": "Animation",
    "rating": 8.5,
    "sequel": "sequel",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p11_zpsde8cd05b.jpg"
    
  },
  {
    "grossing": 1024300000,
    "director": "Tim Burton",
    "movie": "Alice in Wonderland",
    "other": "Remake",
    "main actor": "Johnny Depp",
    "release date": "3/5/2010",
    "studio": "Disney",
    "rank": 2,
    "Academy Awards": "Art Direction, Costume Design",
    "genre": "Family",
    "rating": 6.5,
    "sequel": "remake",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p6_zps2122be31.jpg"
  },
  {
    "grossing": 956400000,
    "director": "David Yates",
    "movie": "Harry Potter and the Deathly Hallows Part 1",
    "other": "From book",
    "main actor": "Daniel Radcliffe",
    "release date": "11/19/2010",
    "studio": "Warner Brothers",
    "rank": 3,
    "Academy Awards": null,
    "genre": "Fantasy",
    "rating": 7.6,
    "sequel": "sequel",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p8_zps4bf83344.jpg"
  },
  {
    "grossing": 845500000,
    "director": "Christopher Nolan",
    "movie": "Inception",
    "other": "Original",
    "main actor": "Leonardo DiCaprio",
    "release date": "7/16/2010",
    "studio": "Warner Brothers",
    "rank": 4,
    "Academy Awards": "Cinamatography, Visual Effects, Sound, Sound Editing",
    "genre": "Sci-Fi",
    "rating": 8.8,
    "sequel": null,
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p7_zpsaacb6c49.jpg"
  },
  {
    "grossing": 752600000,
    "director": "Mike Mitchell",
    "movie": "Shrek Forever After",
    "other": "sequel",
    "main actor": "Mike Meyers",
    "release date": "5/21/2010",
    "studio": "Paramount",
    "rank": 5,
    "Academy Awards": null,
    "genre": "Animation",
    "rating": 6.4,
    "sequel": "sequel",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p10_zps841955b9.jpg"
  },
  {
    "grossing": 1328100000,
    "director": "David Yates",
    "movie": "Harry Potter and the Deathly Hallows Part 2",
    "other": "sequel",
    "main actor": null,
    "release date": "7/15/2011",
    "studio": "Warner Brothers",
    "rank": 1,
    "Academy Awards": null,
    "genre": "Fantasy",
    "rating": 8.1,
    "sequel": "sequel",
    "year": "2011",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p2_zps049394c5.jpg"
  },
  {
    "grossing": 1123700000,
    "director": "Michael Bay",
    "movie": "Transformers: Dark of the Moon",
    "other": "sequel",
    "main actor": "Shia LaBeouf",
    "release date": "6/29/2011",
    "studio": "Paramount",
    "rank": 2,
    "Academy Awards": null,
    "genre": "Sci-Fi",
    "rating": 6.3,
    "sequel": "sequel",
    "year": "2011",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p5_zps74f856f1.jpg"
  },
  {
    "grossing": 1043900000,
    "director": "Rob Marshall",
    "movie": "Pirates of the Carabbean: On Stranger Tides",
    "other": "sequel",
    "main actor": "Johnny Depp",
    "release date": "5/20/2011",
    "studio": "Disney",
    "rank": 3,
    "Academy Awards": null,
    "genre": "Adventure",
    "rating": 6.6,
    "sequel": "sequel",
    "year": "2011",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p4_zps8acb5ef9.jpg"
  },
  {
    "grossing": 712200000,
    "director": "Bill Cordon",
    "movie": "The Twilight Saga: Breaking Dawn Part 1",
    "other": "sequel",
    "main actor": "Robert Pattinson",
    "release date": "11/18/2011",
    "studio": "Summit Entertainment",
    "rank": 4,
    "Academy Awards": null,
    "genre": "Romance",
    "rating": 4.8,
    "sequel": "sequel",
    "year": "2011",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p1_zps170f8631.jpg"
  },
  {
    "grossing": 694700000,
    "director": "Brad Bird",
    "movie": "Mission Impossible: Ghost Protocol",
    "other": "sequel",
    "main actor": "Tom Cruise",
    "release date": "12/16/2011",
    "studio": "Paramount",
    "rank": 5,
    "Academy Awards": null,
    "genre": "Action",
    "rating": 7.4,
    "sequel": "sequel",
    "year": "2011",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p3_zps98ae5337.jpg"
    
  },
  {
    "grossing": 1511800000,
    "director": "Joss Whedon",
    "movie": "Marvel's The Avengers",
    "other": "sequel",
    "main actor": "Robert Downey Jr.",
    "release date": "4/4/2012",
    "studio": "Disney",
    "rank": 1,
    "Academy Awards": null,
    "genre": "Action",
    "rating": 8.3,
    "year": "2012",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p18_zpsffccbee1.jpg"
  },
  {
    "grossing": 1094300000,
    "director": "Sam Mendes",
    "movie": "Skyfall",
    "other": "sequel",
    "main actor": "Daniel Craig",
    "release date": "11/9/2012",
    "studio": "Sony/ Columbia",
    "rank": 2,
    "Academy Awards": null,
    "genre": "Action",
    "rating": 7.9,
    "sequel": null,
    "year": "2012",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p20_zps23ec8a39.jpg"
  },
  {
    "grossing": 1081000000,
    "director": "Christopher Nolan",
    "movie": "The Dark Knight Rises",
    "other": "sequel",
    "main actor": "Christian Bale",
    "release date": "7/20/2012",
    "studio": "Warner Brothers",
    "rank": 3,
    "Academy Awards": null,
    "genre": "Action",
    "rating": 8.7,
    "sequel": "sequel",
    "year": "2012",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p22_zps74bb2406.jpg"
  },
  {
    "grossing": 950200000,
    "director": "Peter Jackson",
    "movie": "The Hobbit: An Unexpected Journey",
    "other": "From book",
    "main actor": "Martin Freeman",
    "release date": "12/14/2012",
    "studio": "Warner Brothers",
    "rank": 4,
    "Academy Awards": null,
    "genre": "Fantasy",
    "rating": 8.3,
    "sequel": null,
    "year": "2012",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p21_zps9e9725b6.jpg"
  },
  {
    "grossing": 875300000,
    "director": "Eric Darnell",
    "movie": "Ice Age: Continental Drift",
    "other": "sequel",
    "main actor": "Ray Romano",
    "release date": "7/13/2012",
    "studio": "Fox",
    "rank": 5,
    "Academy Awards": null,
    "genre": "Animation",
    "rating": 6.6,
    "sequel": "sequel",
    "year": "2012",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/p17_zps8595100b.jpg"
    
  },
    {
    "movie": "MADAGASCAR",
    "other": "Sequel",
    "studio": "Paramount",
    "genre": "Animation",
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-06at113318PM_zps122ba59f.png"  
  },
    {
    "movie": "Quantum of Solace",
    "other": "Sequel",
    "studio": "Sony/ Columbia",
    "genre": "Action",
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-06at113632PM_zps8c694319.png"  
  },
    {
    "movie": "Iron man",

    "other": "From book",
    "studio": "Paramount",
    "genre": "Action",
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-06at113919PM_zps4f2bdca0.png"  
  },
    {
    "movie": "Wall E",

    "other": "Original",
    "studio": "Buena Vista",
    "genre": "Animation",
    "year": "2008",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-06at113904PM_zps6b642f58.png"  
  },
    {
    "movie": "UP",

    "other": "Original",
    "studio": "Buena Vista",
    "genre": "Animation",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-08at123230PM_zps3e4bb1c5.png"  
  },
      {
    "movie": "Andels & Demons",

    "other": "Original",
    "studio": "Sony/ Columbia",
    "genre": "Thriller",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-08at123428PM_zps37cb036f.png"  
  },
      {
    "movie": "Twilight Saga: New moon",

    "other": "Sequel",
    "studio": "Summit Entrainment",
    "genre": "Romance",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/twilight_saga_new_moon_xlg_zpsf751b4c4.jpg"  
  },
      {
    "movie": "Sherlock Holmes",

    "other": "From book",
    "studio": "Warner Brothers",
    "genre": "Adventure",
    "year": "2009",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/Sherlock-Holmes-Poster_zps81a9168a.jpg"  
  },
      {
    "movie": "Despicable Me",

    "other": "Original",
    "studio": "Universal",
    "genre": "Animation",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/despicablemeposter05_zpsc8d7af98.jpg"  
  },
      {
    "movie": "Tangled",

    "other": "Original",
    "studio": "Buena Vista",
    "genre": "Animation",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-08at124323PM_zpsd494a139.png"  
  },
      {
    "movie": "Ironman2",

    "other": "Sequel",
    "studio": "Paramount",
    "genre": "Action",
    "year": "2010",
    "image": "http://i1344.photobucket.com/albums/p658/ktengprawat/ScreenShot2013-05-08at124309PM_zps440b1bb6.png"  
  }
  
]
